name: "BMS Pace - Development"
description: "Pace BMS Interface"
version: "0.1dev"
slug: "bms_pace_dev"
url: "https://github.com/simons1008/bmspace"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

options:
  connection_type: "Serial"
  bms_ip: "10.0.0.161"
  bms_port: 5000
  bms_serial: "/dev/ttyUSB0"
  scan_interval: 5
  debug_output: 0
  debug_output2: 0
  force_pack_offset: 0
  zero_pad_number_cells: 0
  zero_pad_number_packs: 0
schema:
  connection_type: list(IP|Serial)
  bms_ip: str
  bms_port: int
  bms_serial: str
  scan_interval: int
  debug_output: int
  debug_output2: int
  force_pack_offset: "int?"
  zero_pad_number_cells: "int?"
  zero_pad_number_packs: "int?"
